export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const MOVE_PRODUCT = "MOVE_PRODUCT";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";