export const ALL_SECTION_REQUEST = "ALL_SECTION_REQUEST";
export const ALL_SECTION_FAIL = "ALL_SECTION_FAIL";
export const ALL_SECTION_SUCCESS = "ALL_SECTION_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
