export const ALL_SECTION_REQUEST = "ALL_SECTION_REQUEST";
export const ALL_SECTION_FAIL = "ALL_SECTION_FAIL";
export const ALL_SECTION_SUCCESS = "ALL_SECTION_SUCCESS";

export const NEW_SECTION_REQUEST = "NEW_SECTION_REQUEST";
export const NEW_SECTION_SUCCESS = "NEW_SECTION_SUCCESS";
export const NEW_SECTION_RESET = "NEW_SECTION_RESET";
export const NEW_SECTION_FAIL = "NEW_SECTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
