export const ALL_WAREHOUSE_REQUEST = "ALL_WAREHOUSE_REQUEST";
export const ALL_WAREHOUSE_FAIL = "ALL_WAREHOUSE_FAIL";
export const ALL_WAREHOUSE_SUCCESS = "ALL_WAREHOUSE_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
