export const ALL_WAREHOUSE_REQUEST = "ALL_WAREHOUSE_REQUEST";
export const ALL_WAREHOUSE_FAIL = "ALL_WAREHOUSE_FAIL";
export const ALL_WAREHOUSE_SUCCESS = "ALL_WAREHOUSE_SUCCESS";

export const NEW_WAREHOUSE_REQUEST = "NEW_WAREHOUSE_REQUEST";
export const NEW_WAREHOUSE_SUCCESS = "NEW_WAREHOUSE_SUCCESS";
export const NEW_WAREHOUSE_RESET = "NEW_WAREHOUSE_RESET";
export const NEW_WAREHOUSE_FAIL = "NEW_WAREHOUSE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
